### ISSUE TITLE
Can't move/copy files (and maybe also other related actions)

### ISSUE THREAD

**Issue by danimesq** [C2Electron/c2-plugin#6]
@Armaldio

When trying to copy a image:
![image](https://user-images.githubusercontent.com/6765277/50378666-c6773f00-061e-11e9-9683-7dd0f3593cde.png)

It gives this error:
> Uncaught (in promise) TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.resolve (path.js:186:7)
>     at Object.copy (C:\Program Files (x86)\ElectronForC2\resources\app\node_modules\fs-extra\lib\copy\copy.js:28:27)
>     at Promise (C:\Program Files (x86)\ElectronForC2\resources\app\node_modules\universalify\index.js:13:12)
>     at Promise (<anonymous>)
>     at Object.copy (C:\Program Files (x86)\ElectronForC2\resources\app\node_modules\universalify\index.js:7:14)
>     at pluginProto.Instance.Acts.CopySync (http://localhost:50002/armaldio_electron_plugin.js:449:8)
>     at Action.run_object (http://localhost:50002/eveng.js:1852:10)
>     at EventBlock.resume_actions_and_subevents (http://localhost:50002/eveng.js:947:38)
>     at cr.system_object.sysProto.runWaits (http://localhost:50002/system.js:3006:9)

**Comment by Armaldio** [comment]
I'll try to look into this quickly
Is it related to [this](https://github.com/ElectronForConstruct/construct2-plugin/issues/4)?

**Comment by DaniellMesquita** [comment]
I don't think its related, as on the referred issue, user is trying to put a file system path onto a variable
